### ISSUE TITLE
Add PHP 8 support

### ISSUE THREAD

**Issue by danilakorovin** [MonstreX/voyager-extension#25]
Hello!
Very interesting package for Voyager.
Is it possible to add PHP 8 support? It'll require to upgrade spatie/laravel-medialibrary to v9 as well.

`- spatie/laravel-medialibrary[8.0.0, ..., 8.10.1] require php ^7.4 -> your php version (8.0.6) does not satisfy that requirement.`

Thank you! 
All the best.

**Comment by MonstreX** [comment]
Hello there.
Thank you for you interest for this package. The Voyager Extension works on php v8. As well as media-library since version 8.10.2. Try to install the fresh latest laravel version,  then the latest Voyager version, then Voyager Extension. It should work. I've tried recently and it has been installed without any errors.
```json
    "require": {
        "php": "^7.3|^8.0",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.65",
        "laravel/sanctum": "^2.11",
        "laravel/tinker": "^2.5",
        "monstrex/voyager-extension": "^0.93.0",
        "monstrex/voyager-site": "^0.93.0",
        "tcg/voyager": "^1.5"
    },
```

**Comment by danilakorovin** [comment]
Sorry, my fault. 
The problem was with composer.lock and other packages installed before.

`composer update` 

solved the problem.

Thank you.
